# main menu
[[main]]
name = "Home"
url = "/"
weight = 1

[[main]]
name = "Blog"
url = "blog"
weight = 2

[[main]]
name = "Prețuri"
url = "preturi"
weight = 3

[[main]]
name = "Contact"
url = "contact"
weight = 4

[[main]]
name = "FAQ"
url = "faq"
weight = 5

# footer menu left
[[footer_left]]
name = "Despre noi"
url = "#"

[[footer_left]]
name = "Pornire rapidă"
url = "#"

[[footer_left]]
name = "Prețuri"
url = "preturi"


# footer menu middle
[[footer_middle]]
name = "Prețuri"
url = "preturi"

[[footer_middle]]
name = "Platform"
url = "#"

[[footer_middle]]
name = "Features"
url = "#"

# footer menu right
[[footer_right]]
name = "Privacy Policy"
url = "privacy-policy"

[[footer_right]]
name = "Terms & Conditions"
url = "terms-conditions"

[[footer_right]]
name = "FAQ"
url = "faq"