---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: heading
  label: heading
- type: heading
  label: Homepage
- type: document
  path: exampleSite/content/english/_index.md
  label: Homepage (en)
- type: document
  path: exampleSite/content/deutsch/_index.md
  label: Homepage (de)
- type: document
  path: exampleSite/content/romana/_index.md
  label: Homepage (ro)
- type: heading
  label: Blog
- type: document
  path: exampleSite/content/english/blog/_index.md
  label: Blog Page (en)
- type: document
  path: exampleSite/content/deutsch/blog/_index.md
  label: Blog Page (de)
- type: document
  path: exampleSite/content/romana/blog/_index.md
  label: Blog Page (ro)
- type: directory
  path: exampleSite/content/english/blog
  label: Blog Post (en)
  create: documents
  match: "**/*"
  exclude: _index.md
  templates:
  - post
- type: directory
  path: exampleSite/content/deutsch/blog
  label: Blog Post (de)
  create: documents
  match: "**/*"
  exclude: _index.md
  templates:
  - post
- type: directory
  path: exampleSite/content/romana/blog
  label: Blog Post (ro)
  create: documents
  match: "**/*"
  exclude: _index.md
  templates:
  - post
- type: heading
  label: Others Page
- type: document
  path: exampleSite/content/english/contact/_index.md
  label: Contact (en)
- type: document
  path: exampleSite/content/deutsch/contact/_index.md
  label: Contact (de)
- type: document
  path: exampleSite/content/romana/contact/_index.md
  label: Contact (ro)
- type: document
  path: exampleSite/content/english/pricing/_index.md
  label: Pricing (en)
- type: document
  path: exampleSite/content/deutsch/pricing/_index.md
  label: Pricing (de)
- type: document
  path: exampleSite/content/romana/pricing/_index.md
  label: Pricing (ro)
- type: document
  path: exampleSite/content/english/faq/_index.md
  label: FAQ (en)
- type: document
  path: exampleSite/content/deutsch/faq/_index.md
  label: FAQ (de)
- type: document
  path: exampleSite/content/romana/faq/_index.md
  label: FAQ (ro)
- type: heading
  label: All Pages
- type: directory
  path: exampleSite/content
  label: All Pages
  create: all
  match: "**/*"
  exclude: _index.md
  templates:
  - new-page
- type: heading
  label: Configuration
- type: document
  path: exampleSite/config/_default/config.toml
  label: Configuration
- type: document
  path: exampleSite/config/_default/params.toml
  label: Parameters
- type: document
  path: config.toml
  label: Variables & Plugins
- type: document
  path: exampleSite/config/_default/languages.toml
  label: Languages
- type: document
  path: exampleSite/config/_default/menus.en.toml
  label: Menu (en)
- type: document
  path: exampleSite/config/_default/menus.de.toml
  label: Menu (de)
- type: document
  path: exampleSite/config/_default/menus.ro.toml
  label: Menu (ro)
upload_dir: ''
public_path: ''
front_matter_path: ''
use_front_matter_path: 
file_template: ":filename:"
build:
  preview_env:
  - HUGO_VERSION=0.74.3
  - HUGO_BASEURL=/
  preview_output_directory: public
  preview_docker_image: forestryio/hugo:latest
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: cd exampleSite && hugo server
version: 0.74.3
